# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test_1.proto, test_2.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .google import protobuf


@dataclass
class Test1(betterproto.Message):
    a: str = betterproto.string_field(1)
    b: int = betterproto.int32_field(2)


@dataclass
class Test2(betterproto.Message):
    a: protobuf.Empty = betterproto.message_field(1)
