# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc1.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class Test(betterproto.Message):
    a: str = betterproto.string_field(1)
    b: int = betterproto.int32_field(2)


class Service1Stub(betterproto.ServiceStub):
    async def testing(self, *, a: str = "", b: int = 0) -> Test:
        request = Test()
        request.a = a
        request.b = b

        return await self._unary_unary(
            "/pkg1.Service1/Testing",
            request,
            Test,
        )
